Repository ezbir/ezbir-fe, pull requests merged in 2024-07, with the labels that each got.

#3 2-show-fundraiser
  src/app/profile/components/CreateFundraiserMenu.tsx
  src/app/profile/components/FundraiserForm.tsx
Labels: completed

#6 5-refactoring-auth
  src/app/auth/layout.tsx
  src/app/auth/login/components/LoginForm.tsx
  src/app/auth/login/page.tsx
  src/app/auth/register/page.tsx
  src/app/fundraiser/layout.tsx
  src/app/profile/layout.tsx
  src/app/user/layout.tsx
  src/app/volunteers/layout.tsx
  src/components/auth/AuthAside.tsx
  src/components/auth/OtherAuth.tsx
  src/components/auth/login/LoginForm.func.ts
  src/components/auth/login/LoginForm.tsx
  src/components/auth/register/CheckCode.func.ts
  src/components/auth/register/CheckCode.tsx
  src/components/auth/register/RegForm.func.ts
  src/components/auth/register/RegForm.tsx
Labels: completed, refactoring code

#8 7-refactoring-fundraiser
  package-lock.json
  package.json
  src/app/fundraiser/[slug]/page.tsx
  src/app/fundraiser/components/FundraiserEditForm.tsx
  src/app/fundraiser/page.tsx
  src/app/profile/components/FundraiserForm.tsx
  src/app/profile/page.tsx
  src/app/user/[slug]/page.tsx
  src/components/fundraiser/FundraiserCard.tsx
  src/components/fundraiser/FundraiserCategoryEnum.ts
  src/components/fundraiser/FundraiserEdit.tsx
  src/components/fundraiser/FundraiserEditForm.tsx
  src/components/fundraiser/IFundraiser.ts
Labels: completed, refactoring code

#13 Create nextjs.yml
  .github/workflows/nextjs.yml
Labels: completed

#15 14-fix-bug
  src/app/fundraiser/[slug]/page.tsx
  src/app/fundraiser/layout.tsx
  src/app/fundraiser/page.tsx
  src/app/profile/layout.tsx
  src/app/profile/page.tsx
  src/app/user/[slug]/page.tsx
  src/app/user/layout.tsx
  src/app/volunteers/layout.tsx
  src/components/fundraiser/FundraiserEdit.tsx
Labels: completed

#16 1-fix-fundraiser-deletion
  src/app/profile/page.tsx
  src/components/fundraiser/FundraiserEditForm.func.ts
Labels: completed

#18 11-refactoring-support
  src/app/support/page.tsx
  src/components/support/FAQ.tsx
  src/components/support/ResponseForm.tsx
Labels: completed, refactoring code

#19 10-refactoring-setting
  src/app/setting/layout.tsx
  src/components/setting/SettingAside.tsx
Labels: completed, refactoring code

#20 status update
  src/app/favicon.ico
  src/app/profile/page.tsx
  src/components/fundraiser/CreateFundraiser.tsx
  src/components/fundraiser/CreateFundraiserForm.tsx
  src/components/fundraiser/FundraiserEdit.func.ts
  src/components/fundraiser/FundraiserEdit.tsx
  src/components/fundraiser/FundraiserEditForm.tsx
  src/components/fundraiser/FundraiserForm.tsx
  src/components/fundraiser/IFundraiser.ts
Labels: in-progress, new function

#21 fix-build-app
  src/app/user/[slug]/getServerSideProps.ts
Labels: bug, in-progress

#24 Fix build app
  src/app/fundraiser/[slug]/page.tsx
  src/app/user/[slug]/page.tsx
Labels: bug, completed

#25 Update README.md
  README.md
Labels: documentation, completed

#27 26-connect-the-new-backend
  src/app/fundraiser/page.tsx
  src/app/volunteers/page.tsx
  src/components/auth/login/LoginForm.func.ts
  src/components/auth/register/CheckCode.func.ts
  src/components/auth/register/CheckCode.tsx
  src/components/auth/register/RegForm.func.ts
  src/components/fundraiser/CreateFundraiser.func.ts
  src/components/fundraiser/FundraiserEdit.func.ts
Labels: completed

#28 4-add-float-label-for-input
  src/components/HeaderV2.tsx
  src/components/auth/login/LoginForm.func.ts
  src/components/auth/login/LoginForm.tsx
  src/components/auth/register/CheckCode.tsx
  src/components/auth/register/RegForm.func.ts
  src/components/auth/register/RegForm.tsx
  src/components/fundraiser/FundraiserForm.tsx
Labels: completed, refactoring code

#36 add dockerfile (#35)
  Dockerfile
  package.json
  src/components/auth/login/LoginForm.func.ts
  src/components/auth/register/CheckCode.func.ts
  src/components/auth/register/RegForm.func.ts
  src/components/fundraiser/CreateFundraiser.func.ts
  src/components/fundraiser/FundraiserEdit.func.ts
Labels: new function
